### ISSUE TITLE
Issue while running the project from MainCPG.java file

### ISSUE THREAD

**Issue by Samarjeet93** [Djack1010/GrapPa#1]
soot.CompilationDeathException: Couldn't resolve classpath entry C:\Users\Samarjeet\eclipse-workspace\First_Project\bin\com\test:C:\Users\Samarjeet\Downloads\GrapPa-master\extLib\jdk1.7.0_80\jre\lib\alt-rt.jar:C:\Users\Samarjeet\Downloads\GrapPa-master\extLib\jdk1.7.0_80\jre\lib\charsets.jar:C:\Users\Samarjeet\Downloads\GrapPa-master\extLib\jdk1.7.0_80\jre\lib\deploy.jar:C:\Users\Samarjeet\Downloads\GrapPa-master\extLib\jdk1.7.0_80\jre\lib\javaws.jar:C:\Users\Samarjeet\Downloads\GrapPa-master\extLib\jdk1.7.0_80\jre\lib\jce.jar:C:\Users\Samarjeet\Downloads\GrapPa-master\extLib\jdk1.7.0_80\jre\lib\jfr.jar:C:\Users\Samarjeet\Downloads\GrapPa-master\extLib\jdk1.7.0_80\jre\lib\jfxrt.jar:C:\Users\Samarjeet\Downloads\GrapPa-master\extLib\jdk1.7.0_80\jre\lib\jsse.jar:C:\Users\Samarjeet\Downloads\GrapPa-master\extLib\jdk1.7.0_80\jre\lib\management-agent.jar:C:\Users\Samarjeet\Downloads\GrapPa-master\extLib\jdk1.7.0_80\jre\lib\plugin.jar:C:\Users\Samarjeet\Downloads\GrapPa-master\extLib\jdk1.7.0_80\jre\lib\resource.jar:C:\Users\Samarjeet\Downloads\GrapPa-master\extLib\jdk1.7.0_80\jre\lib\rt.jar: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at soot.SourceLocator.explodeClassPath(SourceLocator.java:168)
	at soot.SourceLocator.getClassSource(SourceLocator.java:179)
	at soot.Scene.tryLoadClass(Scene.java:1030)
	at soot.Scene.loadBasicClasses(Scene.java:1744)
	at soot.Scene.loadNecessaryClasses(Scene.java:1845)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
	at SourceCode.MainCPG.main(MainCPG.java:443)

**Comment by Djack1010** [comment]
Hi there,

'Couldn't resolve classpath entry'

I guess either you are missing libraries or you are not setting properly the environment to get access to them. Take a look at the README file for dependencies and setup information.
